### ISSUE TITLE
Active Record Validations > 3. Common Validation Options

### ISSUE THREAD

**Issue by HenriqueMorato** [campuscode/rails-guides-pt-BR#126]
## Motivação

Tradução do tópico **3. Common Validation Options** da página **<em>Active Record</em> Validações**.

**Comment by douglas-oliveira-talkdesk** [comment]
Olá @HenriqueMorato, vou continuar esta issue 👍

**Comment by HenriqueMorato** [comment]
> Olá @HenriqueMorato, vou continuar esta issue 👍 

Oi @douglas-oliveira-talkdesk tudo bem? Boas vindas ao guia. Já tem uma tradução em andamento dessa issue. Pode pegar outra enquanto dou uma olhada se destravo essa?

**Comment by douglas-oliveira-talkdesk** [comment]
> > Olá @HenriqueMorato, vou continuar esta issue 👍
> 
> Oi @douglas-oliveira-talkdesk tudo bem? Boas vindas ao guia. Já tem uma tradução em andamento dessa issue. Pode pegar outra enquanto dou uma olhada se destravo essa?

Claro, obrigado!

**Comment by douglas-oliveira-talkdesk** [comment]
@HenriqueMorato de qualquer forma, já terminei a tradução. Caso @maugravena não tenha interesse em continuar, me avise que eu submeto o PR. Thanks!

**Comment by HenriqueMorato** [comment]
> @HenriqueMorato de qualquer forma, já terminei a tradução. Caso @maugravena não tenha interesse em continuar, me avise que eu submeto o PR. Thanks!

Aviso sim! Já estou verificando 😄

**Comment by HenriqueMorato** [comment]
Oi, @douglas-oliveira-talkdesk o @maugravena tocou essa tradução.

Mas se quiser as issues #151 e #160 acabaram de ficar disponíveis 😄
