### ISSUE TITLE
.gitignore não inclui arquivos de IDE jetbrains

### ISSUE THREAD

**Issue by joaozeni** [campuscode/rails-guides-pt-BR#14]
## Motivação
Esse arquivos são especificos por usuário.

**Comment by wilkinsondarolt** [comment]
@HenriqueMorato acredito que essa issue já está resolvida, confere?

**Comment by HenriqueMorato** [comment]
> @HenriqueMorato acredito que essa issue já está resolvida, confere?

Confere! Muito obrigado pelo toque @wilkinsondarolt. Agradecemos a contribuição :smile: 

@campuscode/guia-rails-team estou fechando a issue.
