### ISSUE TITLE
Active Record Query Interface > 5. Limit and Offset

### ISSUE THREAD

**Issue by HenriqueMorato** [campuscode/rails-guides-pt-BR#151]
## Motivação

Tradução do tópico **5. Limit and Offset** da página **Active Record Query Interface**.

**Comment by vcborsolan** [comment]
Prezados , darei sequencia na traduçao deste capitulo.

**Comment by HenriqueMorato** [comment]
Oi, @vcborsolan, tudo bom?

Pra travar essa issue com você o ideal é abrir um Pull Request, assim ela fica travada contigo e outras pessoas veem o processo já iniciado 😄

**Comment by vcborsolan** [comment]
Tranquilo @HenriqueMorato  , pode dar sequencia , nesse meio tempo eu mudei de empresa e acabei me enrolando dando sequencia nas traduções.

**Comment by HenriqueMorato** [comment]
> Tranquilo @HenriqueMorato , pode dar sequencia , nesse meio tempo eu mudei de empresa e acabei me enrolando dando sequencia nas traduções.

Tudo bem! Qualquer coisa se tiver interesse de traduzir no futuro só abrir um Pull Request 😄
