### ISSUE TITLE
Active Record Query Interface > 13. Eager Loading Associations

### ISSUE THREAD

**Issue by HenriqueMorato** [campuscode/rails-guides-pt-BR#159]
## Motivação

Tradução do tópico **13. Eager Loading Associations** da página **Active Record Query Interface**.

**Comment by vcborsolan** [comment]
Prezados , darei sequencia na traduçao deste capitulo.

**Comment by HenriqueMorato** [comment]
Oi, @vcborsolan, tudo bom?

Nós não costumamos travar issues via comentário, mas sim quando o pull request é aberto 😢 

Você já começou essa tradução? Porque o @rohan-techfreak já está com uma em processo de revisão então vamos dar preferencia pra ele tudo bem?

**Comment by vcborsolan** [comment]
Tranquilo @HenriqueMorato  , pode dar sequencia , nesse meio tempo eu mudei de empresa e acabei me enrolando dando sequencia nas traduções
