### ISSUE TITLE
Action View Form Helpers > 6. Customizing Form Builders

### ISSUE THREAD

**Issue by HenriqueMorato** [campuscode/rails-guides-pt-BR#177]
## Motivação

Tradução do tópico **6. Customizing Form Builders** da página **Action View Form Helpers**.

**Comment by tomascco** [comment]
Opa, vou pegar essa issue.

**Comment by HenriqueMorato** [comment]
Fique a vontade @tomascco! Agradecemos bastante.

Quando você começar pode mudar o título do tópico e já abrir o pull request marcando a issue, assim ela fica travada com você e evita que outras pessoas trabalhem em duplicidade.

**Comment by tomascco** [comment]
Ok, valeu pela dica, vou fazer isso.
