### ISSUE TITLE
Action View Form Helpers > 8. Forms to External Resources

### ISSUE THREAD

**Issue by HenriqueMorato** [campuscode/rails-guides-pt-BR#179]
## Motivação

Tradução do tópico **8. Forms to External Resources** da página **Action View Form Helpers**.

**Comment by marcospedro97** [comment]
Posso pegar essa issue?

**Comment by HenriqueMorato** [comment]
Oi @marcospedro97 parace não ter nenhum pull request aberto pra essa issue.

Pode pegar sim! Agradeceríamos bastante 😄 

Lembre-se de abrir um pull request em draft bem no inicio do trabalho ficar aqui marcado que você já começou essa issue assim outras pessoas podem ver também.

**Comment by marcospedro97** [comment]
OK, farei merge da master mais atual com o fork que já tenho do projeto e abrirei o PR
