### ISSUE TITLE
Action Controller Overview > 6. Cookies

### ISSUE THREAD

**Issue by HenriqueMorato** [campuscode/rails-guides-pt-BR#187]
## Motivação

Tradução do tópico **6. Cookies** da página **Action Controller Overview**.

**Comment by maugravena** [comment]
Olá @HenriqueMorato, eu gostaria de traduzir essa parte.

**Comment by HenriqueMorato** [comment]
> Olá @HenriqueMorato, eu gostaria de traduzir essa parte.

Manda brasa, só lembra de marcar o PR aqui pra outra pessoa não pegar a issue :smile:
