### ISSUE TITLE
Getting Started > Correção de alguns typos de TIP/NOTES

### ISSUE THREAD

**Issue by marcelakopko** [campuscode/rails-guides-pt-BR#231]
## Motivação

Getting Started > Correção de alguns typos de TIP/NOTES

**Comment by marcelakopko** [comment]
https://github.com/campuscode/rails-guides-pt-BR/pull/228

**Comment by wilkinsondarolt** [comment]
@HenriqueMorato acredito que essa issue já está resolvida, confere?

**Comment by HenriqueMorato** [comment]
> @HenriqueMorato acredito que essa issue já está resolvida, confere?

Está sim! Fechando!
