### ISSUE TITLE
Debugging Rails Applications > 5. Sending Messages

### ISSUE THREAD

**Issue by grun00** [campuscode/rails-guides-pt-BR#26]
## Motivação

Tradução do tópico 5 da página debugging

**Comment by wilkinsondarolt** [comment]
@HenriqueMorato acredito que essa issue já está resolvida, confere?

**Comment by HenriqueMorato** [comment]
> @HenriqueMorato acredito que essa issue já está resolvida, confere?

Confere! Muito obrigado pelo toque @wilkinsondarolt. Agradecemos a contribuição :smile: 

@campuscode/guia-rails-team estou fechando a issue.
