### ISSUE TITLE
working with javascript > 4. Server-Side Concerns

### ISSUE THREAD

**Issue by oliveira-andre** [campuscode/rails-guides-pt-BR#317]
## Motivação

Tradução do tópico **4. Server-Side Concerns** da página **working with javascript**.

**Comment by marcospedro97** [comment]
Posso pegar essa issue?

**Comment by HenriqueMorato** [comment]
> Posso pegar essa issue?

Oi, @marcospedro97 , acho que essa issue tava mal linkada em um pull request mas fiz um merge hoje que fecha ela. Então ela já foi traduzida
