### ISSUE TITLE
Action Mailer Basics > 2. Sending Emails

### ISSUE THREAD

**Issue by HenriqueMorato** [campuscode/rails-guides-pt-BR#382]
## Motivação

Tradução do tópico **2. Sending Emails** da página **Action Mailer Basics**.

Essa pode ser quebrada em duas por ser um pouco grande caso alguém queira traduzir 😄

**Comment by VinyLimaZ** [comment]
Vou começar esse capitulo!

**Comment by VinyLimaZ** [comment]
Me comprometo em criar mais 1 PR e completar a tradução desse capitulo! :D

**Comment by HenriqueMorato** [comment]
Mantive a issue permanece aberta porque a tradução foi quebrada em duas partes 😄
