### ISSUE TITLE
Active Job Basics > 2. The Purpose of Active Job

### ISSUE THREAD

**Issue by HenriqueMorato** [campuscode/rails-guides-pt-BR#386]
## Motivação

Tradução do tópico **2. The Purpose of Active Job** da página **Active Job Basics**.

**Comment by MarcusAldrey** [comment]
olá, estou fazendo a tradução e gostaria de saber se eu deveria traduzir:
jobs 
background jobs 
queue

**Comment by tkusuki** [comment]
> olá, estou fazendo a tradução e gostaria de saber se eu deveria traduzir:
> jobs
> background jobs
> queue

Eu sugiro que ***jobs*** e ***background jobs*** não sejam traduzidos, por ser os termos que utilizamos no dia a dia (não esqueça de deixá-los em itálico, pois manteremos o termos em inglês).

Para *background jobs* podemos só dar um contexto em português apenas a primeira vez que o termo aparecer. Exemplo:

```
How to run jobs in the background
Como executar *jobs* em *background* (segundo plano).
```

***Queue*** eu sugiro traduzir para fila mesmo, pois é como nos referimos também no dia a dia.

O que vocês acham @campuscode/guia-rails-team ?
