### ISSUE TITLE
Debugging Rails Applications > 6. Debugging with the byebug gem

### ISSUE THREAD

**Issue by maugravena** [campuscode/rails-guides-pt-BR#40]
## Motivação

Tradução do tópico **6. Debugging with the byebug gem** da página **Debugging Rails Applications**.

**Comment by maugravena** [comment]
Aguardando revisão

**Comment by wilkinsondarolt** [comment]
@HenriqueMorato acredito que essa issue já está resolvida, confere?

**Comment by HenriqueMorato** [comment]
> @HenriqueMorato acredito que essa issue já está resolvida, confere?

Está sim! Vou fechar. Agradecemos o toque :smile:
