### ISSUE TITLE
Using Rails for API-only Applications > 3 The Basic Configuration

### ISSUE THREAD

**Issue by IngridRodrigues15** [campuscode/rails-guides-pt-BR#44]
## Motivação

Tradução do tópico **3 The Basic Configuration** da página *Using Rails for API-only Applications**.

**Comment by IngridRodrigues15** [comment]
Fazendo no pull request https://github.com/campuscode/rails-guides-pt-BR/pull/45

**Comment by wilkinsondarolt** [comment]
@HenriqueMorato acredito que essa issue já está resolvida, confere?

**Comment by HenriqueMorato** [comment]
> @HenriqueMorato acredito que essa issue já está resolvida, confere?

Está sim! Vou fechar. Agradecemos o toque :smile:
