### ISSUE TITLE
Configuring Rails Applications > Rails General Configuration

### ISSUE THREAD

**Issue by joaorsalmeida** [campuscode/rails-guides-pt-BR#57]
## Motivação

Tradução do tópico **Rails General Configuration** da página **Configuring Rails Applications**.

**Comment by wilkinsondarolt** [comment]
@HenriqueMorato acredito que essa issue já está resolvida, confere?

**Comment by HenriqueMorato** [comment]
> @HenriqueMorato acredito que essa issue já está resolvida, confere?

Confere! Muito obrigado pelo toque @wilkinsondarolt. Agradecemos a contribuição :smile: 

@campuscode/guia-rails-team estou fechando a issue.

**Comment by Guillerbr** [comment]
Existe um guia tutorial para seguir, afim de aprender como o processo de tradução deve ser feito?

**Comment by HenriqueMorato** [comment]
> Existe um guia tutorial para seguir, afim de aprender como o processo de tradução deve ser feito?

Tem sim! No README tem algumas informações que você pode ler [aqui](https://github.com/campuscode/rails-guides-pt-BR#como-ajudar).

Mas vou dar uma resumida:

- Fork do repositório
- Clonar o repositório do Fork
- Verificar no https://guiarails.com.br o que deseja traduzir, recomendamos a tradução de um tópico de página. Exemplo: **1. The Object Life Cycle** da página **Active Record Callbacks**
- Verifique se a issue dessa página já existe e se alguém já está executando a tradução da mesma
- Criar seu novo branch para a tradução
- Iniciar a tradução da página no arquivo da pasta pt-BR/ (recomendo abrir o Pull Request em Draft assim que começar e marcar a issue para evitar problemas)
- Fazer commits a vontade e quando terminar mudar o Pull Request para Open
- Esperar o Review e Merge

Acho que é isso se tiver qualquer dúvida do processo você pode abrir uma issue, esperamos você por aqui :smile:
