### ISSUE TITLE
Active View Overview > 1 What is Action View?

### ISSUE THREAD

**Issue by leokassio** [campuscode/rails-guides-pt-BR#597]
## Motivação

Tradução do tópico **1. What is Action View?** da página **Active View Overview**.

**Comment by leokassio** [comment]
quero trabalhar nisso como parte do Hacktoberfest

**Comment by tkusuki** [comment]
> gostaria de trabalhar nisso como parte do Hacktoberfest

Olá @leokassio , tudo bem?
Essa issue já foi traduzida, entrou no PR https://github.com/campuscode/rails-guides-pt-BR/pull/544
