### ISSUE TITLE
Active Record Validations > 5. Conditional Validation

### ISSUE THREAD

**Issue by IngridRodrigues15** [campuscode/rails-guides-pt-BR#76]
## Motivação

Tradução do tópico ** 5. Conditional Validation** da página **Active Record Validations**.

**Comment by wilkinsondarolt** [comment]
@HenriqueMorato acredito que essa issue já está resolvida, confere?

**Comment by HenriqueMorato** [comment]
> @HenriqueMorato acredito que essa issue já está resolvida, confere?

Confere! Muito obrigado pelo toque @wilkinsondarolt. Agradecemos a contribuição :smile: 

@campuscode/guia-rails-team estou fechando a issue.
